# Generated by Django 2.2.5 on 2019-09-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(blank=True, max_length=20, null=True)),
                ('Nachricht', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pinned_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=20)),
                ('Nachricht', models.TextField()),
            ],
        ),
    ]
